### ISSUE TITLE
What if there are some dynamic obstacles?

### ISSUE THREAD

**Issue by linxigjs** [XiaojingGeorgeZhang/H-OBCA#1]
Hi, I think your method is brilliant! However, I think it will work only in a static environment. It calculates the parking trajectory after the driver finds a parking spot and stops the car nearly. So what would happen if there are some dynamic obstacles? If the planning is quickly enough, maybe we can update the map and environment with dynamic obstacles' new pose, but this planning method usually runs for several seconds.
Hope for your help! Thanks!

**Comment by alexliniger** [comment]
Whereas it is simple to make the obstacle dynamic for the OBCA part by changing the static matrices A and b to time varying matrices (A and b should be different for each time step). I don't know directly how to implement a Hybrid A* with dynamic obstacles, but I assume someone has a solution.Maybe there exist easier ways to generate warm starts with dynamic obstacles.

Note that even the OBCA formulation is a bit tricky to implement if you optimize over the sampling time.

Best,
Alex

**Comment by linxigjs** [comment]
> Whereas it is simple to make the obstacle dynamic for the OBCA part by changing the static matrices A and b to time varying matrices (A and b should be different for each time step). I don't know directly how to implement a Hybrid A* with dynamic obstacles, but I assume someone has a solution.Maybe there exist easier ways to generate warm starts with dynamic obstacles.

Thank you for your interesting idea. So we can choose another global planner that figures out the dynamic obstacles to give OBCA a proper warm start, while the optimization has no need to change. Is my understanding right? However, the slow calculation is a big problem ...

**Comment by alexliniger** [comment]
you need to change the code a bit but not the general formulation.
We never tried to run OBCA in a receding horizon fashion, but using the previous solution as a warm start could potentially help a lot.
